os: osx
 
language: node_js
 
node_js:
  - "node"
 
before_install:
  - brew update
  - brew cask install sketch # install Sketch 
  - mkdir -p "~/Library/Application Support/com.bohemiancoding.sketch3" # create support folder 
  - mkdir -p "~/Library/Application Support/com.bohemiancoding.sketch3/Plugins" # create plugins folder 

cache:
  directories:
    - "node_modules"
    - $HOME/Library/Caches/Homebrew
 
script:
  - npm run test
